### PR TITLE
Match GNOME builder menus

### PR DESCRIPTION
**Pull request by bellegarde-c**

### CODE REVIEW

**Comment by bellegarde-c** [comment]
Not sure about this one, may need a special case because menu item height looks wrong.

**Comment by lassekongo83** [comment]
Any app specific CSS classes should go in `_apps.scss`

Like:

**_apps.scss**
```scss
// GNOME Builder menus
.dzlmenubutton {
  @extend %menu;
}
.dzlmenubuttonitem {
  @extend %menuitem;
}
```

And in `_common.scss`:
```scss
menu,
.menu,
%menu,
.context-menu {

...

  menuitem,
  %menuitem {
    min-height: 16px;
    min-width: 40px;
    padding: 4px 6px;
    text-shadow: none;
    font-weight: normal

...
```

**Comment by bellegarde-c** [comment]
Ok, thanks, giving a look.

**Comment by bellegarde-c** [comment]
I may be stupid but overriding height does not seem to work? I can define a new property but not override one already defined in %menuitem.

**Pull request merged**
